# Generated by Django 4.2.2 on 2023-08-31 14:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
