# Generated by Django 4.2.2 on 2023-08-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
