# Generated by Django 4.2.2 on 2023-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0006_user_orderline_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
