# Generated by Django 4.2.2 on 2023-09-04 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0007_remove_orderline_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.product')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.vendingmachineslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
