# Generated by Django 4.2.2 on 2023-09-04 14:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
